import {supabase} from "./supabase";
export async function getFeed(){const{data,error}=await supabase.from("posts").select("id,user_id,body,created_at,profiles(full_name,username,avatar_url),post_media(id,media_type,media_url,thumbnail_url,sort_order),post_likes(user_id),comments(id,user_id,body,created_at)").order("created_at",{ascending:false}).limit(30);if(error)throw error;return data||[]}
export async function createPost(body){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{data,error}=await supabase.from("posts").insert({user_id:user.id,body}).select().single();if(error)throw error;return data}
export async function toggleLike(postId,liked){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const q=supabase.from("post_likes");const r=liked?await q.delete().eq("post_id",postId).eq("user_id",user.id):await q.insert({post_id:postId,user_id:user.id});if(r.error)throw r.error}
export async function addComment(postId,body){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{error}=await supabase.from("comments").insert({post_id:postId,user_id:user.id,body});if(error)throw error}
export async function toggleFollow(userId,following){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");if(user.id===userId)throw new Error("CANNOT_FOLLOW_SELF");const r=following?await supabase.from("follows").delete().eq("follower_id",user.id).eq("following_id",userId):await supabase.from("follows").insert({follower_id:user.id,following_id:userId});if(r.error)throw r.error}
export async function toggleBlock(userId,blocked){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");if(user.id===userId)throw new Error("CANNOT_BLOCK_SELF");const r=blocked?await supabase.from("blocks").delete().eq("blocker_id",user.id).eq("blocked_id",userId):await supabase.from("blocks").insert({blocker_id:user.id,blocked_id:userId});if(r.error)throw r.error}
export async function searchProfiles(query,limit=20){const{data,error}=await supabase.rpc("search_profiles",{p_query:query,p_limit:limit});if(error)throw error;return data||[]}
export async function getFollowState(userId){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const[{data:f},{data:b}]=await Promise.all([supabase.from("follows").select("follower_id").eq("follower_id",user.id).eq("following_id",userId).maybeSingle(),supabase.from("blocks").select("blocker_id").eq("blocker_id",user.id).eq("blocked_id",userId).maybeSingle()]);return{following:!!f,blocked:!!b}}
export async function toggleSavedPost(postId,saved){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const r=saved?await supabase.from("saved_posts").delete().eq("post_id",postId).eq("user_id",user.id):await supabase.from("saved_posts").insert({post_id:postId,user_id:user.id});if(r.error)throw r.error}
export async function getSavedPostIds(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{data,error}=await supabase.from("saved_posts").select("post_id").eq("user_id",user.id);if(error)throw error;return(data||[]).map(x=>x.post_id)}
export async function repostPost(postId,reposted){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const r=reposted?await supabase.from("post_reposts").delete().eq("post_id",postId).eq("user_id",user.id):await supabase.from("post_reposts").insert({post_id:postId,user_id:user.id});if(r.error)throw r.error}
export async function attachPostMedia(postId,media){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{error}=await supabase.from("post_media").insert(media.map((m,i)=>({post_id:postId,media_type:m.media_type,media_url:m.media_url,thumbnail_url:m.thumbnail_url||null,sort_order:i})));if(error)throw error}
export async function createStory(media_type,media_url,expires_at){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{error}=await supabase.from("stories").insert({user_id:user.id,media_type,media_url,expires_at});if(error)throw error}

export async function getPublicProfile(userId){const{data,error}=await supabase.rpc("get_public_profile",{p_user_id:userId});if(error)throw error;return data}
export async function getProfileConnections(userId,direction,limit=50,offset=0){const{data,error}=await supabase.rpc("get_profile_connections",{p_user_id:userId,p_direction:direction,p_limit:limit,p_offset:offset});if(error)throw error;return data||[]}

export async function getUserPosts(userId){const{data,error}=await supabase.from("posts").select("id,user_id,body,created_at,profiles(full_name,username,avatar_url),post_media(id,media_type,media_url,thumbnail_url,sort_order),post_likes(user_id),comments(id,user_id,body,created_at)").eq("user_id",userId).order("created_at",{ascending:false}).limit(60);if(error)throw error;return data||[]}
export async function getUserReposts(userId){const{data,error}=await supabase.from("post_reposts").select("created_at,posts(id,user_id,body,created_at,profiles(full_name,username,avatar_url),post_media(id,media_type,media_url,thumbnail_url,sort_order),post_likes(user_id),comments(id,user_id,body,created_at))").eq("user_id",userId).order("created_at",{ascending:false}).limit(60);if(error)throw error;return(data||[]).map(x=>({...x.posts,reposted_at:x.created_at})).filter(Boolean)}
export async function getUserSavedPosts(userId){const{data,error}=await supabase.from("saved_posts").select("created_at,posts(id,user_id,body,created_at,profiles(full_name,username,avatar_url),post_media(id,media_type,media_url,thumbnail_url,sort_order),post_likes(user_id),comments(id,user_id,body,created_at))").eq("user_id",userId).order("created_at",{ascending:false}).limit(60);if(error)throw error;return(data||[]).map(x=>({...x.posts,saved_at:x.created_at})).filter(Boolean)}

export async function sendDirectMessage(recipientId,body){const{data,error}=await supabase.rpc("send_direct_message",{p_recipient_id:recipientId,p_body:body});if(error)throw error;return data}
export async function respondMessageRequest(conversationId,accept){const{data,error}=await supabase.rpc("respond_message_request",{p_conversation_id:conversationId,p_accept:accept});if(error)throw error;return data}
export async function getMessageRequests(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{data,error}=await supabase.from("message_requests").select("id,conversation_id,sender_id,recipient_id,status,created_at,profiles:sender_id(id)").eq("recipient_id",user.id).eq("status","pending").order("created_at",{ascending:false});if(error)throw error;const rows=data||[];const ids=[...new Set(rows.map(x=>x.sender_id))];if(!ids.length)return rows.map(x=>({...x,sender:null}));const{data:profiles,error:pe}=await supabase.from("profiles").select("id,username,full_name,avatar_url").in("id",ids);if(pe)throw pe;const byId=Object.fromEntries((profiles||[]).map(p=>[p.id,p]));return rows.map(x=>({...x,sender:byId[x.sender_id]||null}))}
