import {supabase} from "./supabase";
export async function getFeed(){const{data,error}=await supabase.from("posts").select("id,user_id,body,created_at,profiles(full_name,username,avatar_url),post_media(id,media_type,media_url,thumbnail_url,sort_order),post_likes(user_id),comments(id,user_id,body,created_at)").order("created_at",{ascending:false}).limit(30);if(error)throw error;return data||[]}
export async function createPost(body){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{data,error}=await supabase.from("posts").insert({user_id:user.id,body}).select().single();if(error)throw error;return data}
export async function toggleLike(postId,liked){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const q=supabase.from("post_likes");const r=liked?await q.delete().eq("post_id",postId).eq("user_id",user.id):await q.insert({post_id:postId,user_id:user.id});if(r.error)throw r.error}
export async function addComment(postId,body){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{error}=await supabase.from("comments").insert({post_id:postId,user_id:user.id,body});if(error)throw error}
export async function toggleFollow(userId,following){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");if(user.id===userId)throw new Error("CANNOT_FOLLOW_SELF");const r=following?await supabase.from("follows").delete().eq("follower_id",user.id).eq("following_id",userId):await supabase.from("follows").insert({follower_id:user.id,following_id:userId});if(r.error)throw r.error}
export async function toggleBlock(userId,blocked){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");if(user.id===userId)throw new Error("CANNOT_BLOCK_SELF");const r=blocked?await supabase.from("blocks").delete().eq("blocker_id",user.id).eq("blocked_id",userId):await supabase.from("blocks").insert({blocker_id:user.id,blocked_id:userId});if(r.error)throw r.error}
export async function searchProfiles(query,limit=20){const{data,error}=await supabase.rpc("search_profiles",{p_query:query,p_limit:limit});if(error)throw error;return data||[]}
export async function getFollowState(userId){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const[{data:f},{data:b}]=await Promise.all([supabase.from("follows").select("follower_id").eq("follower_id",user.id).eq("following_id",userId).maybeSingle(),supabase.from("blocks").select("blocker_id").eq("blocker_id",user.id).eq("blocked_id",userId).maybeSingle()]);return{following:!!f,blocked:!!b}}
export async function attachPostMedia(postId,media){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{error}=await supabase.from("post_media").insert(media.map((m,i)=>({post_id:postId,media_type:m.media_type,media_url:m.media_url,thumbnail_url:m.thumbnail_url||null,sort_order:i})));if(error)throw error}
export async function createStory(media_type,media_url,expires_at){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const{error}=await supabase.from("stories").insert({user_id:user.id,media_type,media_url,expires_at});if(error)throw error}
