import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {BookOpen,Trophy,Users,Calculator,UserCircle,Home,ChevronRight,LogIn,LogOut,CheckCircle2,ArrowLeft,ArrowRight,Clock,Target} from "lucide-react";
import {supabase,supabaseConfigured} from "./lib/supabase";
import {getExams,getSubjects,getTopics,startCbt,submitCbt} from "./lib/cbt";
import {getCompetitions,joinCompetition,getLeaderboard} from "./lib/competition";
import {getAttemptHistory,getPerformance,getAttemptCorrections} from "./lib/performance";
import "./styles.css";

const fallbackExams=["JAMB","WAEC","NECO","NABTEB","GCE","BECE","IJMB","Post-UTME"];
const fallbackSubjects=["Mathematics","English Language","Physics","Chemistry","Biology","Economics","Government","Accounting"];
const difficulties=["EASY","MEDIUM","HARD"];

function App(){
 const [tab,setTab]=useState("home"),[exam,setExam]=useState(null),[subject,setSubject]=useState(null),[topic,setTopic]=useState(""),[difficulty,setDifficulty]=useState(""),[count,setCount]=useState(10);
 const [exams,setExams]=useState([]),[subjects,setSubjects]=useState([]),[topics,setTopics]=useState([]),[session,setSession]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [quiz,setQuiz]=useState(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[result,setResult]=useState(null);\n const [competitions,setCompetitions]=useState([]),[leaders,setLeaders]=useState([]);\n const [history,setHistory]=useState([]),[performance,setPerformance]=useState([]),[corrections,setCorrections]=useState(null),[historyBusy,setHistoryBusy]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!supabaseConfigured)return;Promise.all([getExams(),getSubjects()]).then(([e,s])=>{setExams(e);setSubjects(s);if(e[0])setExam(e[0]);if(s[0])setSubject(s[0])}).catch(()=>{})},[]);
 useEffect(()=>{if(subject?.id)getTopics(subject.id).then(setTopics).catch(()=>setTopics([]))},[subject]);\n useEffect(()=>{if(supabaseConfigured){getCompetitions().then(setCompetitions).catch(()=>{});getLeaderboard(20).then(setLeaders).catch(()=>{})}},[]);\n useEffect(()=>{if(session){getAttemptHistory().then(setHistory).catch(()=>{});getPerformance().then(setPerformance).catch(()=>{})}},[session]);
 const signIn=async()=>{setBusy(true);setNotice("");const{error}=await supabase.auth.signInWithPassword({email,password});setNotice(error?error.message:"Signed in successfully.");setBusy(false)};
 const signUp=async()=>{setBusy(true);setNotice("");const{error}=await supabase.auth.signUp({email,password});setNotice(error?error.message:"Account created. Check your email if confirmation is enabled.");setBusy(false)};
 const signOut=async()=>{await supabase?.auth.signOut();setNotice("Signed out.")};
 const begin=async()=>{if(!session){setNotice("Please sign in before starting a saved CBT.");setTab("profile");return}if(!exam||!subject){setNotice("Select an exam and subject.");return}setBusy(true);setNotice("");try{const data=await startCbt({examId:exam.id,subjectId:subject.id,topicId:topic||null,difficulty:difficulty||null,questionCount:count});if(!data.questions?.length){setNotice("No published questions match these choices yet.");return}setQuiz(data);setIndex(0);setAnswers({});setResult(null)}catch(e){setNotice(e.message||"Unable to start CBT.")}finally{setBusy(false)}};
 const choose=(optionId)=>setAnswers(a=>({...a,[quiz.questions[index].id]:optionId}));
 const finish=async()=>{setBusy(true);try{const payload=Object.entries(answers).map(([question_id,selected_option_id])=>({question_id,selected_option_id}));const r=await submitCbt(quiz.attempt_id,payload);setResult(r)}catch(e){setNotice(e.message||"Unable to submit CBT.")}finally{setBusy(false)}};
 const examNames=exams.length?exams:fallbackExams.map(name=>({id:null,name})), subjectNames=subjects.length?subjects:fallbackSubjects.map(name=>({id:null,name}));
 return <div className="app"><header><div className="brand"><span className="logo">E</span><div><b>EduToks</b><small>Learn • Create • Compete</small></div></div><button className="profile" onClick={()=>setTab("profile")}><UserCircle/></button></header>
 <main>
 {tab==="home"&&<><section className="hero"><div><span className="pill">🇳🇬 Built for Nigerian students</span><h1>Learn smarter.<br/><em>Compete better.</em></h1><p>CBT practice, competitions, learning tools and a student community in one place.</p><button className="primary" onClick={()=>setTab("cbt")}>Start CBT <ChevronRight size={18}/></button></div><div className="hero-card"><Trophy/><b>Daily Challenge</b><span>Test your knowledge and climb the leaderboard.</span></div></section><h2>Explore EduToks</h2><div className="cards"><Card icon={<BookOpen/>} title="CBT Practice" text="JAMB, WAEC, NECO & more" onClick={()=>setTab("cbt")}/><Card icon={<Trophy/>} title="Competitions" text="Earn points and rank up" onClick={()=>setTab("competition")}/><Card icon={<Calculator/>} title="Study Tools" text="Calculators & learning helpers" onClick={()=>setTab("tools")}/><Card icon={<Users/>} title="Community" text="Connect with students & teachers" onClick={()=>setTab("community")}/></div></>}
 {tab==="cbt"&&(!quiz?<section className="panel"><h1>CBT Practice</h1><p>Build your real practice session.</p><label>Exam</label><div className="chips">{examNames.map(x=><button className={exam?.id===x.id?"chip active":"chip"} onClick={()=>setExam(x)} key={x.id||x.name}>{x.name}</button>)}</div><label>Subject</label><select value={subject?.id||subject?.name||""} onChange={e=>setSubject(subjectNames.find(x=>String(x.id||x.name)===e.target.value))}>{subjectNames.map(x=><option key={x.id||x.name} value={x.id||x.name}>{x.name}</option>)}</select><label>Topic</label><select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{topics.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label>Difficulty</label><div className="chips">{difficulties.map(x=><button className={difficulty===x?"chip active":"chip"} onClick={()=>setDifficulty(difficulty===x?"":x)} key={x}>{x}</button>)}</div><label>Questions: {count}</label><input type="range" min="5" max="50" step="5" value={count} onChange={e=>setCount(Number(e.target.value))}/><div className="practice"><b>{exam?.name||"Exam"} • {subject?.name||"Subject"}</b><span>{session?"Ready to save your attempt.":"Sign in to save your attempt and earn points."}</span><button className="primary" disabled={busy} onClick={begin}>{busy?"Starting…":"Start Practice"}</button></div></section>:!result?<section className="panel quiz"><div className="quiz-head"><span><Target/> Question {index+1} of {quiz.questions.length}</span><span><Clock/> Practice</span></div><div className="progress"><i style={{width:((index+1)/quiz.questions.length*100)+"%"}}/></div><h2>{quiz.questions[index].question_text}</h2>{quiz.questions[index].is_ai_generated&&<span className="pill">AI-generated practice</span>}<div className="options">{quiz.questions[index].options.map(o=><button key={o.id} className={answers[quiz.questions[index].id]===o.id?"option selected":"option"} onClick={()=>choose(o.id)}>{o.option_key}. {o.option_text}</button>)}</div><div className="quiz-actions">{index>0&&<button className="secondary" onClick={()=>setIndex(index-1)}><ArrowLeft/> Previous</button>}{index<quiz.questions.length-1?<button className="primary" onClick={()=>setIndex(index+1)}><ArrowRight/> Next</button>:<button className="primary" disabled={busy} onClick={finish}>{busy?"Submitting…":"Submit CBT"}</button>}</div></section>:<section className="panel result"><CheckCircle2/><h1>CBT Complete</h1><div className="score">{result.score}/{quiz.questions.length}</div><p>{result.correct_count} correct • {result.points_earned} points earned</p><button className="primary" onClick={()=>{setQuiz(null);setResult(null);setAnswers({});setIndex(0)}}>Take Another Practice</button></section>)}
 {tab==="competition"&&<section className="panel"><h1>Competitions & Leaderboard</h1><p>Compete and climb the EduToks rankings.</p><div className="cards">{competitions.map(c=><div className="card" key={c.id}><Trophy/><b>{c.name}</b><span>{c.description}</span><button className="primary" onClick={async()=>{if(!session){setNotice("Please sign in to join.");return}try{await joinCompetition(c.id);setNotice("Joined competition.");}catch(e){setNotice(e.message)}}}>Join</button></div>)}</div><h2>Points Leaderboard</h2><div className="leaderboard">{leaders.map((x,i)=><div className="stat" key={x.user_id}><b>#{i+1}</b><div><b>{x.full_name||x.username||"Student"}</b><span>{x.points} points</span></div></div>)}</div></section>}
 {tab==="tools"&&<section className="panel"><h1>Study Tools</h1><div className="tool-grid">{subjectNames.slice(0,6).map(x=><div className="tool" key={x.id||x.name}><Calculator/><b>{x.name} Calculator</b><span>Equation-ready study helper</span></div>)}</div></section>}
 {tab==="community"&&<section className="panel"><h1>Community</h1><p>Social feed, creators, teachers, stories, chat and live learning will use persistent data.</p><div className="empty">Community layer next.</div></section>}
 {tab==="performance"&&<section className="panel"><h1>My Performance</h1><p>Your real CBT progress and accuracy.</p><div className="cards">{performance.map(x=><div className="stat" key={x.subject_name}><Target/><div><b>{x.subject_name||"General"}</b><span>{x.accuracy}% accuracy • {x.attempts} attempts</span></div></div>)}</div><h2>CBT History</h2>{history.map(x=><div className="stat" key={x.id}><div><b>{x.exam_name||"Exam"} • {x.subject_name||"Subject"}</b><span>{x.correct_count}/{x.question_count} correct • Score {x.score}</span></div><button className="secondary" onClick={async()=>{setHistoryBusy(true);try{setCorrections(await getAttemptCorrections(x.id))}finally{setHistoryBusy(false)}}}>{historyBusy?"Loading…":"Corrections"}</button></div>)}{corrections&&<div className="corrections"><h2>Corrections</h2>{corrections.map((c,i)=><div className="correction" key={c.question_id}><b>{i+1}. {c.questions?.question_text}</b><span>{c.is_correct?"✓ Correct":"✗ Incorrect"}</span>{c.questions?.explanation&&<small>{c.questions.explanation}</small>}<div>{c.questions?.question_options?.map(o=><div key={o.id} className={o.is_correct?"correct-answer":o.id===c.selected_option_id?"chosen-answer":""}>{o.option_key}. {o.option_text}</div>)}</div></div>)}</div>}</section>}
 {tab==="profile"&&<section className="panel"><h1>{session?"Your Profile":"Sign in to EduToks"}</h1>{session?<><div className="stat"><CheckCircle2/><div><b>Authenticated</b><span>{session.user.email}</span></div></div><button className="secondary" onClick={signOut}><LogOut/> Sign out</button></>:<><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><div className="auth-actions"><button className="primary" disabled={!supabaseConfigured||busy} onClick={signIn}><LogIn/> Sign in</button><button className="secondary" disabled={!supabaseConfigured||busy} onClick={signUp}>Create account</button></div>{!supabaseConfigured&&<small>Add Supabase site variables.</small>}</>}</section>}
 {notice&&<div className="notice">{notice}</div>}
 </main><nav>{[["home",<Home/>,"Home"],["cbt",<BookOpen/>,"CBT"],["performance",<Target/>,"Results"],["competition",<Trophy/>,"Compete"],["community",<Users/>,"Community"],["tools",<Calculator/>,"Tools"]].map(([id,icon,label])=><button className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)} key={id}>{icon}<span>{label}</span></button>)}</nav></div>
}
function Card({icon,title,text,onClick}){return <button className="card" onClick={onClick}>{icon}<b>{title}</b><span>{text}</span><ChevronRight/></button>}
createRoot(document.getElementById("root")).render(<App/>);